name: Check

on:
  pull_request:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@f4d14e03ff726c06358e5557344e1da148b56cf7 # v1.2.2

      - name: Install Dependencies
        run: bun install

      - name: Check
        run: bun check

      - name: Commit and Push
        run: |
          git add --intent-to-add .
          if ! git diff --exit-code --quiet
          then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add --all
            git commit --author=. --message="fix: auto-fix"
            git push
          fi
