name: Check

on:
  pull_request:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2

      - name: Install Dependencies
        run: bun install

      - name: Check
        run: bun check

      - name: Commit and Push
        run: |
          git add --intent-to-add .
          if ! git diff --exit-code --quiet
          then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add --all
            git commit --author=. --message="fix: auto-fix"
            git push
          fi
